# Generated by Django 5.1 on 2026-07-28 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero banner displayed on the brand detail page.",
                null=True,
                upload_to="brands/banners/",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="display_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Lower numbers appear first.",
                verbose_name="Display Order",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="full_description",
            field=models.TextField(blank=True, verbose_name="Full Description"),
        ),
        migrations.AddField(
            model_name="brand",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Featured Brand"),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="brand",
            name="short_description",
            field=models.CharField(blank=True, max_length=500, verbose_name="Short Description"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, verbose_name="Legacy Description"),
        ),
        migrations.CreateModel(
            name="BrandPageBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "title",
                    models.CharField(
                        default="Our Trusted Brands", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True,
                        default="Explore premium dental brands trusted by clinics and professionals worldwide.",
                        verbose_name="Subtitle",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/page_banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        default="Explore Brands",
                        max_length=100,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True,
                        default="#brands-grid",
                        max_length=255,
                        verbose_name="Button Link",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Page Banner",
                "verbose_name_plural": "Brand Page Banners",
            },
        ),
    ]
