# Generated by Django 5.1 on 2026-08-12 06:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_productpricing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpricing",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Harmonised System of Nomenclature code. Required for GST invoices.",
                max_length=20,
                verbose_name="HSN Code",
            ),
        ),
        migrations.AddField(
            model_name="productpricing",
            name="tax_inclusive",
            field=models.BooleanField(
                default=True,
                help_text="If True (default), all admin-entered prices include GST. GST is extracted at checkout, not added on top.",
                verbose_name="Tax Inclusive Pricing",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="dealer_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="GST-inclusive wholesale price for verified dealers only. Must be ≤ Selling Price.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Dealer Price (GST Inclusive)",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                help_text="Applicable GST slab (0, 5, 12, 18, 28). All selling prices are GST-INCLUSIVE.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="GST Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="offer_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Temporary discounted GST-inclusive price. Must be ≤ Selling Price.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Offer Price (GST Inclusive)",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final customer-facing price INCLUDING GST. Must be ≤ MRP. Example: if taxable value is ₹1,000 and GST is 18%, enter ₹1,180.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Selling Price (GST Inclusive)",
            ),
        ),
    ]
