# Generated by Django 5.1 on 2026-08-13 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_gst_inclusive_fields"),
        ("products", "0006_product_is_returnable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(fields=["selling_price"], name="pricing_pro_selling_f29f89_idx"),
        ),
    ]
