# Generated by Django 5.2.15 on 2026-07-23 11:14

import apps.warranty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0002_warrantyregistration_admin_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrantyregistration",
            name="invoice",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="warranty_invoices/%Y/%m/",
                validators=[apps.warranty.models.validate_invoice_file],
                verbose_name="Purchase Invoice",
            ),
        ),
    ]
