# Generated by Django 5.2.15 on 2026-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0003_alter_warrantyregistration_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrantyregistration",
            name="warranty_status",
            field=models.CharField(
                choices=[
                    ("pending_activation", "Pending Activation"),
                    ("pending_registration", "Pending Registration"),
                    ("pending_verification", "Pending Verification"),
                    ("need_more_info", "Need More Info"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending_registration",
                max_length=50,
                verbose_name="Warranty Status",
            ),
        ),
    ]
