# Generated by Django 5.1 on 2026-07-30 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("PUSH", "Push Notification"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "db_table": "notification_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("AUTHENTICATION", "Authentication"),
                    ("ORDERS", "Orders"),
                    ("SUPPORT", "Support"),
                    ("WARRANTY", "Warranty"),
                    ("DEALER", "Dealer"),
                    ("OFFERS", "Offers"),
                    ("SYSTEM", "System"),
                ],
                db_index=True,
                default="SYSTEM",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional unique key to guarantee duplicate-prevention.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_NEW_DEVICE", "New Device Login"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("MOBILE_VERIFIED", "Mobile Verified"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                    ("ORDER_PLACED", "Order Placed"),
                    ("PAYMENT_SUCCESS", "Payment Successful"),
                    ("ORDER_CONFIRMED", "Order Confirmed"),
                    ("ORDER_PACKED", "Order Packed"),
                    ("ORDER_SHIPPED", "Order Shipped"),
                    ("OUT_FOR_DELIVERY", "Out For Delivery"),
                    ("ORDER_DELIVERED", "Order Delivered"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("REFUND_INITIATED", "Refund Initiated"),
                    ("REFUND_COMPLETED", "Refund Completed"),
                    ("SUPPORT_CREATED", "Support Ticket Created"),
                    ("SUPPORT_REPLY", "Support Ticket Reply"),
                    ("SUPPORT_CLOSED", "Support Ticket Closed"),
                    ("WARRANTY_REGISTERED", "Warranty Registered"),
                    ("WARRANTY_APPROVED", "Warranty Approved"),
                    ("DEALER_APPROVED", "Dealer Application Approved"),
                    ("DEALER_REJECTED", "Dealer Application Rejected"),
                    ("COUPON_RECEIVED", "Coupon Received"),
                    ("PRODUCT_BACK_IN_STOCK", "Product Back In Stock"),
                    ("FLASH_SALE", "Flash Sale Alert"),
                ],
                db_index=True,
                default="ORDER_PLACED",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("NORMAL", "Normal"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="NORMAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_7336fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "category"], name="notificatio_user_id_bc55e7_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "notification_type"], name="notificatio_user_id_63f199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "expires_at"], name="notificatio_user_id_3648e6_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="notifications.notification",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification", "channel"], name="notificatio_notific_31045d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["channel", "status"], name="notificatio_channel_169003_idx"),
        ),
    ]
