# Generated by Django 5.1 on 2026-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdelivery_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('ORDERS', 'Orders'), ('SUPPORT', 'Support'), ('WARRANTY', 'Warranty'), ('DEALER', 'Dealer'), ('OFFERS', 'Offers'), ('REVIEWS', 'Reviews'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOGIN_NEW_DEVICE', 'New Device Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('MOBILE_VERIFIED', 'Mobile Verified'), ('EMAIL_VERIFIED', 'Email Verified'), ('ORDER_PLACED', 'Order Placed'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_PACKED', 'Order Packed'), ('ORDER_SHIPPED', 'Order Shipped'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed'), ('SUPPORT_CREATED', 'Support Ticket Created'), ('SUPPORT_REPLY', 'Support Ticket Reply'), ('SUPPORT_CLOSED', 'Support Ticket Closed'), ('WARRANTY_REGISTERED', 'Warranty Registered'), ('WARRANTY_APPROVED', 'Warranty Approved'), ('DEALER_APPROVED', 'Dealer Application Approved'), ('DEALER_REJECTED', 'Dealer Application Rejected'), ('REVIEW_APPROVED', 'Review Approved'), ('REVIEW_REJECTED', 'Review Rejected'), ('COUPON_RECEIVED', 'Coupon Received'), ('PRODUCT_BACK_IN_STOCK', 'Product Back In Stock'), ('FLASH_SALE', 'Flash Sale Alert')], db_index=True, default='ORDER_PLACED', max_length=64),
        ),
    ]
