# Generated by Django 5.1 on 2026-08-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_saved_for_later',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Saved For Later'),
        ),
    ]
