# Generated by Django 5.1 on 2026-08-14 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Category Name")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "db_table": "blog_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Tag Name")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
            ],
            options={
                "verbose_name": "Blog Tag",
                "verbose_name_plural": "Blog Tags",
                "db_table": "blog_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Article Title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("excerpt", models.TextField(blank=True, verbose_name="Short Summary / Excerpt")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Article Content (HTML/Rich-Text)"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/featured/%Y/%m/",
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "featured_image_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="External / Fallback Featured Image URL",
                    ),
                ),
                (
                    "author_name_override",
                    models.CharField(
                        blank=True,
                        help_text="Custom author name (e.g. 'Dr. Rahul Sharma' or 'FAAZO Engineering Team')",
                        max_length=150,
                        verbose_name="Author Display Name Override",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Publish Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Featured Article"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Published At Date/Time"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=255, verbose_name="SEO Meta Title"),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="SEO Meta Description"),
                ),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=255, verbose_name="SEO Meta Keywords"),
                ),
                (
                    "canonical_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Canonical URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author User",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "db_table": "blog_posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"], name="blog_posts_status_35de98_idx"
                    ),
                    models.Index(fields=["slug"], name="blog_posts_slug_b4ca25_idx"),
                    models.Index(
                        fields=["is_featured", "status"], name="blog_posts_is_feat_12acbb_idx"
                    ),
                ],
            },
        ),
    ]
