# Generated by Django 5.1 on 2026-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_admin_notes_userprofile_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Consecutive failed login attempts.",
                verbose_name="Failed Login Attempts",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last successful login.",
                null=True,
                verbose_name="Last Login At",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Account locked until this timestamp.",
                null=True,
                verbose_name="Locked Until",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when terms & conditions were accepted.",
                null=True,
                verbose_name="Terms Accepted At",
            ),
        ),
    ]
