# Generated by Django 5.1 on 2026-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_failed_login_attempts_user_last_login_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("email", "Email & Password"), ("google", "Google OAuth")],
                db_index=True,
                default="email",
                max_length=20,
                verbose_name="Authentication Provider",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique Subject ID assigned by Google OAuth 2.0.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Google Subject ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(
                blank=True,
                help_text="URL to user's Google avatar or uploaded profile image.",
                max_length=500,
                null=True,
                verbose_name="Profile Picture URL",
            ),
        ),
    ]
