# Generated by Django 5.1 on 2026-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_auth_provider_user_google_sub_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is Deleted"),
        ),
    ]
