from django.urls import path
from .views import (
    AdminShipmentCreateView,
    AdminShipmentListView,
    AdminShipmentDetailView,
    AdminShipmentSyncView,
    AdminSchedulePickupView,
    AdminCancelShipmentView,
    AdminShipmentLabelView,
    AdminShipmentManifestView,
    AdminShipmentBulkActionView,
    AdminShipmentExportView,
    AdminFulfillmentStatsView,
    AdminProviderHealthCheckView,
    AdminUpdatePackingStatusView,
    AdminCreateCourierShipmentView,
    CustomerShipmentTrackingView,
    ShiprocketWebhookView,
    DelhiveryWebhookView,
    PincodeServiceabilityView,
    ShippingCostCalculateView,
    AdminShipmentRetryView,
)

urlpatterns = [
    # ── Pincode & Shipping Cost Endpoints ────────────────────
    path(
        "shipping/pincode-check/",
        PincodeServiceabilityView.as_view(),
        name="shipping-pincode-check",
    ),
    path(
        "shipping/check-serviceability/",
        PincodeServiceabilityView.as_view(),
        name="shipping-check-serviceability",
    ),
    path(
        "shipping/calculate-cost/",
        ShippingCostCalculateView.as_view(),
        name="shipping-calculate-cost",
    ),

    # ── Admin Shipment Endpoints ─────────────────────────────
    path(
        "shipping/admin/health/",
        AdminProviderHealthCheckView.as_view(),
        name="admin-shipping-health",
    ),
    path(
        "shipping/admin/shipments/",
        AdminShipmentListView.as_view(),
        name="admin-shipment-list",
    ),
    path(
        "shipping/admin/shipments/create/",
        AdminShipmentCreateView.as_view(),
        name="admin-shipment-create",
    ),
    path(
        "shipping/admin/shipments/bulk-action/",
        AdminShipmentBulkActionView.as_view(),
        name="admin-shipment-bulk-action",
    ),
    path(
        "shipping/admin/shipments/export/",
        AdminShipmentExportView.as_view(),
        name="admin-shipment-export",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/",
        AdminShipmentDetailView.as_view(),
        name="admin-shipment-detail",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/sync/",
        AdminShipmentSyncView.as_view(),
        name="admin-shipment-sync",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/retry/",
        AdminShipmentRetryView.as_view(),
        name="admin-shipment-retry",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/schedule-pickup/",
        AdminSchedulePickupView.as_view(),
        name="admin-shipment-pickup",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/cancel/",
        AdminCancelShipmentView.as_view(),
        name="admin-shipment-cancel",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/label/",
        AdminShipmentLabelView.as_view(),
        name="admin-shipment-label",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/manifest/",
        AdminShipmentManifestView.as_view(),
        name="admin-shipment-manifest",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/update-packing/",
        AdminUpdatePackingStatusView.as_view(),
        name="admin-shipment-update-packing",
    ),
    path(
        "shipping/admin/shipments/<uuid:pk>/create-courier/",
        AdminCreateCourierShipmentView.as_view(),
        name="admin-shipment-create-courier",
    ),
    path(
        "shipping/admin/stats/",
        AdminFulfillmentStatsView.as_view(),
        name="admin-fulfillment-stats",
    ),

    # ── Customer Shipment Tracking ───────────────────────────
    path(
        "orders/<uuid:order_pk>/shipment/",
        CustomerShipmentTrackingView.as_view(),
        name="customer-shipment-tracking",
    ),

    # ── Shiprocket & Legacy Webhooks ─────────────────────────
    path(
        "shipping/webhooks/shiprocket/",
        ShiprocketWebhookView.as_view(),
        name="shiprocket-webhook",
    ),
    path(
        "shipping/webhooks/delhivery/",
        DelhiveryWebhookView.as_view(),
        name="delhivery-webhook",
    ),
]
