# Generated by Django 5.1 on 2026-08-03 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_status_alter_orderstatushistory_status'),
        ('products', '0004_product_average_rating_product_rating_distribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Rating (1-5)')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('comment', models.TextField(verbose_name='Review Content')),
                ('pros', models.TextField(blank=True, default='', verbose_name='Pros')),
                ('cons', models.TextField(blank=True, default='', verbose_name='Cons')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would Recommend')),
                ('is_verified_purchase', models.BooleanField(db_index=True, default=True, verbose_name='Verified Purchase')),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], db_index=True, default='pending', max_length=20, verbose_name='Moderation Status')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Votes')),
                ('unhelpful_count', models.PositiveIntegerField(default=0, verbose_name='Unhelpful Votes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order', verbose_name='Verified Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(verbose_name='Is Helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.productreview', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review Helpful Vote',
                'verbose_name_plural': 'Review Helpful Votes',
                'db_table': 'review_helpful_votes',
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='Media Type')),
                ('file', models.FileField(upload_to='reviews/%Y/%m/', verbose_name='File')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reviews/thumbnails/%Y/%m/', verbose_name='Thumbnail')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reviews.productreview', verbose_name='Review')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Review Media',
                'verbose_name_plural': 'Review Media Attachments',
                'db_table': 'review_media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status', '-created_at'], name='product_rev_product_adfc46_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user', '-created_at'], name='product_rev_user_id_8f61bf_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating', 'status'], name='product_rev_rating_3c66af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulvote',
            unique_together={('review', 'user')},
        ),
    ]
