# Generated by Django 5.1 on 2026-07-27 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100, verbose_name="Action")),
                (
                    "status",
                    models.CharField(
                        db_index=True, default="SUCCESS", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Address"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Event Details"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["action", "status"], name="audit_logs_action_d96607_idx"),
                    models.Index(fields=["created_at"], name="audit_logs_created_262184_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Session Key / Token JTI",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        default="Unknown Device", max_length=255, verbose_name="Device Name"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Address"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is Active"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last Active At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Session",
                "verbose_name_plural": "Device Sessions",
                "db_table": "device_sessions",
                "ordering": ["-last_active_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="device_sess_user_id_026746_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OTPRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        db_index=True,
                        help_text="E.164 phone number or email address",
                        max_length=255,
                        verbose_name="Target (Mobile / Email)",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("password_reset", "Password Reset"),
                            ("login", "Login"),
                        ],
                        db_index=True,
                        default="registration",
                        max_length=50,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "otp_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the 6-digit OTP code.",
                        max_length=128,
                        verbose_name="OTP Hash (SHA-256)",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="Expires At")),
                (
                    "is_used",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is Used"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Verification Attempts"),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=3, verbose_name="Max Allowed Attempts"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Request IP Address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Record",
                "verbose_name_plural": "OTP Records",
                "db_table": "otp_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "purpose", "is_used"],
                        name="otp_records_target_5f0828_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_used"], name="otp_records_expires_333c16_idx"
                    ),
                ],
            },
        ),
    ]
