# Generated by Django 5.1 on 2026-07-27 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auditlog_devicesession_otprecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user"], name="audit_logs_user_id_73c422_idx"),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(
                fields=["user", "expires_at"], name="device_sess_user_id_1c8897_idx"
            ),
        ),
    ]
