# Generated by Django 5.2.15 on 2026-07-23 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_productinventory_options_and_more"),
        ("products", "0003_product_serial_number_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productinventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", 0)),
                name="product_inventory_current_stock_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productinventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_stock__gte", 0)),
                name="product_inventory_reserved_stock_non_negative",
            ),
        ),
    ]
