# Generated by Django 5.2.15 on 2026-07-23 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_productinventory_product_inventory_current_stock_non_negative_and_more",
        ),
        ("products", "0003_product_serial_number_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productinventory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allow_backorders", True),
                    ("reserved_stock__lte", models.F("current_stock")),
                    _connector="OR",
                ),
                name="product_inventory_no_oversell_without_backorder",
            ),
        ),
    ]
