# Generated by Django 5.1 on 2026-07-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_product_serial_number_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestSellerBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional heading displayed over the banner image",
                        max_length=200,
                        verbose_name="Banner Title",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Optional short description displayed over the banner image",
                        max_length=300,
                        verbose_name="Banner Subtitle",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="High-resolution hero image (Desktop ~420px height, Mobile ~220px height)",
                        null=True,
                        upload_to="bestsellers/banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional call-to-action button label (e.g. 'Explore Collection')",
                        max_length=100,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True,
                        help_text="Optional URL or route (e.g. '/products' or '/combos')",
                        max_length=500,
                        verbose_name="Button Redirect Link",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable or disable banner display on the storefront without deleting",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Best Seller Banner",
                "verbose_name_plural": "Best Seller Banners",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BestSellerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first (e.g. 1, 2, 3)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable or disable product visibility in Best Sellers module",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bestseller_entries",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Best Seller Product",
                "verbose_name_plural": "Best Seller Products",
                "ordering": ["display_order", "-created_at"],
                "unique_together": {("product",)},
            },
        ),
    ]
