# Generated by Django 5.1 on 2026-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_serial_number_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='{"1": 0, "2": 0, "3": 0, "4": 0, "5": 0}', verbose_name='Rating Distribution'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total Approved Reviews'),
        ),
    ]
