# Generated by Django 5.1 on 2026-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productsharelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_returnable",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Determines if product is eligible for return/replacement under company policy.",
                verbose_name="Is Returnable",
            ),
        ),
    ]
