# Generated by Django 5.1 on 2026-08-03 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(default='HelpCircle', max_length=50, verbose_name='Icon Name')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'faq_categories',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('answer', models.TextField(verbose_name='Answer Content (Markdown Supported)')),
                ('action_button_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Action Button Label')),
                ('action_button_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Action Button Target URL')),
                ('action_button_type', models.CharField(blank=True, choices=[('track_order', 'Track Order'), ('view_orders', 'View Orders'), ('retry_payment', 'Retry Payment'), ('request_return', 'Request Return'), ('custom_link', 'Custom Link')], default='custom_link', max_length=30)),
                ('icon_name', models.CharField(default='HelpCircle', max_length=50, verbose_name='Icon Name')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(db_index=True, default=True, verbose_name='Featured on Support Center Landing')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('unhelpful_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='support.faqcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'db_table': 'faq_items',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='support.faqitem')),
            ],
            options={
                'verbose_name': 'FAQ Feedback',
                'verbose_name_plural': 'FAQ Feedback Entries',
                'db_table': 'faq_feedback',
            },
        ),
    ]
