# Generated by Django 5.2.15 on 2026-07-23 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_cancellation_reason_order_cancelled_at_and_more"),
        ("users", "0004_userprofile_admin_notes_userprofile_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "-created_at"], name="order_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "-created_at"], name="order_status_created_idx"),
        ),
    ]
