# Generated by Django 5.2.15 on 2026-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_order_user_created_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("shipment_created", "Shipment Created"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("shipment_created", "Shipment Created"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
