# Generated by Django 5.2.15 on 2026-07-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_status_alter_orderstatushistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("fulfilled", "Fulfilled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                    ("packed", "Packed"),
                    ("fulfilled", "Fulfilled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
