# Generated by Django 5.1 on 2026-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status_alter_orderstatushistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cgst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Central GST (intra-state orders only). Zero for inter-state.",
                max_digits=12,
                null=True,
                verbose_name="CGST Amount",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gst_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="GST Rate % (Snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="hsn_code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="HSN Code (Snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="igst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Integrated GST (inter-state orders only). Zero for intra-state.",
                max_digits=12,
                null=True,
                verbose_name="IGST Amount",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_intra_state",
            field=models.BooleanField(
                blank=True,
                help_text="True = warehouse state matches delivery state (CGST+SGST). False = IGST.",
                null=True,
                verbose_name="Intra-State Order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sgst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="State GST (intra-state orders only). Zero for inter-state.",
                max_digits=12,
                null=True,
                verbose_name="SGST Amount",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="taxable_subtotal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="taxable_value_per_unit x quantity",
                max_digits=12,
                null=True,
                verbose_name="Taxable Subtotal",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="taxable_value_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pre-tax value per unit = price / (1 + gst_rate/100)",
                max_digits=12,
                null=True,
                verbose_name="Taxable Value Per Unit",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_gst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="cgst + sgst + igst for this line.",
                max_digits=12,
                null=True,
                verbose_name="Total GST Amount",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Purchase Unit Price (GST Inclusive)"
            ),
        ),
    ]
