# Generated by Django 5.1 on 2026-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_gst_inclusive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="taxable_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="GST-exclusive product value",
                max_digits=12,
                verbose_name="Taxable Subtotal (GST Exclusive)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="selling_subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Selling Subtotal (GST Inclusive)"
            ),
        ),
    ]
