# Generated by Django 5.1 on 2026-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_taxable_subtotal_alter_order_selling_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Shipping Address Snapshot"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Shipping City"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(default="India", max_length=50, verbose_name="Shipping Country"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_full_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Shipping Full Name"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_line1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Shipping Address Line 1"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_line2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Shipping Address Line 2"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_mobile",
            field=models.CharField(blank=True, max_length=20, verbose_name="Shipping Mobile"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_pincode",
            field=models.CharField(blank=True, max_length=10, verbose_name="Shipping Pincode"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100, verbose_name="Shipping State"),
        ),
    ]
