# Generated by Django 5.1 on 2026-08-20 06:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_shipping_address_snapshot_order_shipping_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Event identifier (e.g. ORDER_PLACED, ORDER_CONFIRMED)",
                        max_length=64,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        db_index=True,
                        default="Order",
                        help_text="Aggregate root entity type",
                        max_length=64,
                    ),
                ),
                (
                    "aggregate_id",
                    models.CharField(
                        db_index=True,
                        help_text="PK of the aggregate entity (e.g. order_id)",
                        max_length=128,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data required for background processing",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key ensuring duplicate events are discarded at the database level",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "next_retry_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Outbox Event",
                "verbose_name_plural": "Outbox Events",
                "db_table": "outbox_events",
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"], name="outbox_even_status_315626_idx"
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="outbox_even_aggrega_d56a15_idx",
                    ),
                    models.Index(
                        fields=["event_type", "status"], name="outbox_even_event_t_707000_idx"
                    ),
                ],
            },
        ),
    ]
