# Generated by Django 5.1 on 2026-09-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_outboxevent"),
        ("users", "0007_address_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.address",
                verbose_name="Shipping Address",
            ),
        ),
    ]
