# Generated by Django 5.1 on 2026-09-16 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cod_collectable_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="COD Collectable Amount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cod_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="COD Collection Fee",
            ),
        ),
    ]
