# Generated by Django 5.2.15 on 2026-07-23 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_cancellation_reason_order_cancelled_at_and_more"),
        ("shipping", "0002_shipment_api_status_code_shipment_error_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DelhiveryWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "webhook_id",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Webhook Transaction ID",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        default="verified", max_length=50, verbose_name="HMAC Verification Status"
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict, verbose_name="Raw Webhook Payload")),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Received At"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Processed At"),
                ),
                ("is_processed", models.BooleanField(default=False, verbose_name="Is Processed")),
                ("retry_count", models.IntegerField(default=0, verbose_name="Retry Count")),
                (
                    "processing_result",
                    models.TextField(blank=True, default="", verbose_name="Processing Result"),
                ),
            ],
            options={
                "verbose_name": "Delhivery Webhook Log",
                "verbose_name_plural": "Delhivery Webhook Logs",
                "ordering": ["-received_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="api_status_code",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="execution_time_ms",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="request_payload",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="request_timestamp",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="response_payload",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="response_timestamp",
        ),
        migrations.AddField(
            model_name="shipment",
            name="cod_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="COD Collection Amount (₹)",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="courier_reference",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Courier Reference"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="current_hub",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Current Hub"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="delivery_type",
            field=models.CharField(
                default="Express Surface", max_length=50, verbose_name="Delivery Type"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="dispatch_location",
            field=models.CharField(
                default="Mumbai Fulfillment Hub", max_length=200, verbose_name="Dispatch Location"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=10.0, max_digits=8, verbose_name="Height (cm)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Deleted (Soft)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="label_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Shipping Label URL"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="length",
            field=models.DecimalField(
                decimal_places=2, default=10.0, max_digits=8, verbose_name="Length (cm)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="manifest_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Manifest URL"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="packed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Packed At"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="packed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packed_shipments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Packed By",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="packing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("packing", "Packing"),
                    ("packed", "Packed"),
                    ("qc_passed", "QC Passed"),
                    ("ready_for_pickup", "Ready for Pickup"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Packing Status",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="qc_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="QC At"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="qc_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qc_shipments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="QC By",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Shipment Number",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Shipping Charges (₹)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="volumetric_weight",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=8, verbose_name="Volumetric Weight (kg)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="warehouse",
            field=models.CharField(
                default="FAAZO Central Warehouse - Hub 1",
                max_length=150,
                verbose_name="Warehouse / Fulfillment Center",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=8, verbose_name="Weight (kg)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="width",
            field=models.DecimalField(
                decimal_places=2, default=10.0, max_digits=8, verbose_name="Width (cm)"
            ),
        ),
        migrations.AddField(
            model_name="shipmenttrackingevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("offline", "Offline Simulation"),
                    ("sandbox", "Delhivery Sandbox"),
                    ("live", "Delhivery Live"),
                ],
                db_index=True,
                default="sandbox",
                max_length=20,
                verbose_name="Shipping Provider",
            ),
        ),
        migrations.AlterField(
            model_name="shipmenttrackingevent",
            name="event_source",
            field=models.CharField(
                choices=[
                    ("api_poll", "API Poll"),
                    ("webhook", "Delhivery Webhook"),
                    ("manual", "Manual Admin"),
                    ("system", "System Process"),
                ],
                default="api_poll",
                max_length=50,
                verbose_name="Event Source",
            ),
        ),
        migrations.AlterField(
            model_name="shipmenttrackingevent",
            name="event_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Event Timestamp"
            ),
        ),
        migrations.CreateModel(
            name="ShippingAPILog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("endpoint", models.CharField(max_length=300, verbose_name="API Endpoint")),
                (
                    "request_method",
                    models.CharField(default="POST", max_length=10, verbose_name="HTTP Method"),
                ),
                (
                    "request_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Request Payload"),
                ),
                (
                    "response_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Response Payload"),
                ),
                ("http_status", models.IntegerField(verbose_name="HTTP Status Code")),
                ("latency_ms", models.IntegerField(default=0, verbose_name="Execution Time (ms)")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Error Message"),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_logs",
                        to="shipping.shipment",
                        verbose_name="Shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping API Log",
                "verbose_name_plural": "Shipping API Logs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
