# Generated by Django 5.2.15 on 2026-07-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_delhiverywebhooklog_remove_shipment_api_status_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="needs_review",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Needs Admin Review"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipment_status",
            field=models.CharField(
                choices=[
                    ("not_created", "Not Created"),
                    ("created", "Shipment Created"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("picked_up", "Picked Up"),
                    ("reached_hub", "Reached Hub"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("failed_delivery", "Failed Delivery"),
                    ("rto_initiated", "RTO Initiated"),
                    ("rto_in_transit", "RTO In Transit"),
                    ("rto_delivered", "RTO Delivered"),
                    ("cancelled", "Cancelled"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="not_created",
                max_length=30,
                verbose_name="Courier Status",
            ),
        ),
        migrations.AlterField(
            model_name="shipmenttrackingevent",
            name="status_mapped",
            field=models.CharField(
                choices=[
                    ("not_created", "Not Created"),
                    ("created", "Shipment Created"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("picked_up", "Picked Up"),
                    ("reached_hub", "Reached Hub"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("failed_delivery", "Failed Delivery"),
                    ("rto_initiated", "RTO Initiated"),
                    ("rto_in_transit", "RTO In Transit"),
                    ("rto_delivered", "RTO Delivered"),
                    ("cancelled", "Cancelled"),
                    ("lost", "Lost"),
                ],
                max_length=30,
                verbose_name="Mapped Shipment Status",
            ),
        ),
    ]
