# Generated by Django 5.1 on 2026-08-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shipment_not_created_status_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Courier Code'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Courier Contact'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='failure_reason',
            field=models.TextField(blank=True, default='', verbose_name='Failure Reason'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_error_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last Error Code'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='max_retries_exceeded',
            field=models.BooleanField(default=False, verbose_name='Max Retries Exceeded'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='raw_provider_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw Provider Response'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Retry Count'),
        ),
    ]
