# Generated by Django 5.1 on 2026-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0005_shipment_courier_code_shipment_courier_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="courier_name",
            field=models.CharField(
                default="Shiprocket", max_length=100, verbose_name="Courier Name"
            ),
        ),
    ]
