# Generated by Django 5.1 on 2026-08-10 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_status_alter_orderstatushistory_status'),
        ('payments', '0002_payment_payment_user_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('request_type', models.CharField(choices=[('return_refund', 'Return & Refund'), ('return_replacement', 'Return & Replacement')], default='return_refund', max_length=30, verbose_name='Request Type')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_pending', 'Pickup Pending'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_received', 'Item Received'), ('qc_pending', 'QC Pending'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_pending', 'Replacement Pending'), ('replacement_processing', 'Replacement Processing'), ('replacement_shipped', 'Replacement Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=30, verbose_name='Return Status')),
                ('reason', models.CharField(choices=[('damaged', 'Product Damaged in Transit'), ('defective', 'Defective / Not Working'), ('wrong_item', 'Wrong Item Received'), ('wrong_size', 'Wrong Size / Specification'), ('missing_part', 'Missing Parts / Accessories'), ('not_as_described', 'Not as Described'), ('other', 'Other')], max_length=30, verbose_name='Return Reason')),
                ('customer_notes', models.TextField(blank=True, default='', verbose_name='Customer Description')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Review Notes')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Calculated Refund Amount')),
                ('is_inventory_restored', models.BooleanField(default=False, verbose_name='Is Inventory Restored')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Original Order')),
                ('replacement_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_source_returns', to='orders.order', verbose_name='Replacement Order')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('requested_quantity', models.PositiveIntegerField(verbose_name='Requested Quantity')),
                ('approved_quantity', models.PositiveIntegerField(default=0, verbose_name='Approved Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price Snapshot')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Line Refund Amount')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem', verbose_name='Original Order Item')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnEvidence',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', models.FileField(upload_to='returns/evidence/%Y/%m/', verbose_name='Evidence File')),
                ('file_type', models.CharField(default='image/jpeg', max_length=50, verbose_name='File MIME Type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File Size (Bytes)')),
                ('evidence_type', models.CharField(choices=[('product_damage', 'Product Damage Photo'), ('package_damage', 'Package Damage Photo'), ('wrong_item', 'Wrong Item Photo'), ('other', 'Other Evidence')], default='product_damage', max_length=30, verbose_name='Evidence Category')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Evidence',
                'verbose_name_plural': 'Return Evidences',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnEvent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('from_status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_pending', 'Pickup Pending'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_received', 'Item Received'), ('qc_pending', 'QC Pending'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_pending', 'Replacement Pending'), ('replacement_processing', 'Replacement Processing'), ('replacement_shipped', 'Replacement Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30, verbose_name='From Status')),
                ('to_status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_pending', 'Pickup Pending'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_received', 'Item Received'), ('qc_pending', 'QC Pending'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_pending', 'Refund Pending'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('replacement_pending', 'Replacement Pending'), ('replacement_processing', 'Replacement Processing'), ('replacement_shipped', 'Replacement Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30, verbose_name='To Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Event Notes')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor User')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Event',
                'verbose_name_plural': 'Return Events',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('razorpay_refund_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Razorpay Refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Refund Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown_reconciliation', 'Requires Reconciliation')], db_index=True, default='pending', max_length=30, verbose_name='Refund Status')),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Idempotency Key')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Execution Attempts')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='Failure Reason')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Raw Provider Response')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Payment')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('courier_name', models.CharField(default='Delhivery Return', max_length=100, verbose_name='Courier Name')),
                ('awb_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='AWB Number')),
                ('pickup_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('picked_up', 'Picked Up'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30, verbose_name='Pickup Status')),
                ('pickup_scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Pickup Scheduled Date')),
                ('tracking_url', models.URLField(blank=True, null=True, verbose_name='Tracking URL')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Provider Response')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='returns.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Shipment',
                'verbose_name_plural': 'Return Shipments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', '-created_at'], name='return_cust_created_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created_at'], name='return_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='return_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='refund_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refund_payment_status_idx'),
        ),
    ]
