# Generated by Django 5.1 on 2026-09-14 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="returnshipment",
            name="current_location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Current Location"
            ),
        ),
        migrations.AddField(
            model_name="returnshipment",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Synced At"),
        ),
        migrations.AddField(
            model_name="returnshipment",
            name="shiprocket_order_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Shiprocket Return Order ID"
            ),
        ),
        migrations.AddField(
            model_name="returnshipment",
            name="shiprocket_shipment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Shiprocket Return Shipment ID",
            ),
        ),
        migrations.AddField(
            model_name="returnshipment",
            name="shiprocket_status",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Shiprocket Status"
            ),
        ),
        migrations.AlterField(
            model_name="returnevent",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reverse_shipment_created", "Reverse Shipment Created"),
                    ("pickup_pending", "Pickup Pending"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("pickup_attempted", "Pickup Attempted"),
                    ("picked_up", "Picked Up"),
                    ("return_in_transit", "Return in Transit"),
                    ("return_delivered", "Return Delivered"),
                    ("item_received", "Item Received"),
                    ("qc_pending", "QC Pending"),
                    ("qc_passed", "QC Passed"),
                    ("qc_failed", "QC Failed"),
                    ("verification_pending", "Verification Pending"),
                    ("verification_passed", "Verification Passed"),
                    ("verification_failed", "Verification Failed"),
                    ("pickup_failed", "Pickup Failed"),
                    ("return_lost", "Return Lost"),
                    ("refund_pending", "Refund Pending"),
                    ("refund_processing", "Refund Processing"),
                    ("refunded", "Refunded"),
                    ("replacement_pending", "Replacement Pending"),
                    ("replacement_approved", "Replacement Approved"),
                    ("replacement_processing", "Replacement Processing"),
                    ("new_shipment_created", "New Shipment Created"),
                    ("new_shipment_in_transit", "New Shipment in Transit"),
                    ("replacement_shipped", "Replacement Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=30,
                verbose_name="From Status",
            ),
        ),
        migrations.AlterField(
            model_name="returnevent",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reverse_shipment_created", "Reverse Shipment Created"),
                    ("pickup_pending", "Pickup Pending"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("pickup_attempted", "Pickup Attempted"),
                    ("picked_up", "Picked Up"),
                    ("return_in_transit", "Return in Transit"),
                    ("return_delivered", "Return Delivered"),
                    ("item_received", "Item Received"),
                    ("qc_pending", "QC Pending"),
                    ("qc_passed", "QC Passed"),
                    ("qc_failed", "QC Failed"),
                    ("verification_pending", "Verification Pending"),
                    ("verification_passed", "Verification Passed"),
                    ("verification_failed", "Verification Failed"),
                    ("pickup_failed", "Pickup Failed"),
                    ("return_lost", "Return Lost"),
                    ("refund_pending", "Refund Pending"),
                    ("refund_processing", "Refund Processing"),
                    ("refunded", "Refunded"),
                    ("replacement_pending", "Replacement Pending"),
                    ("replacement_approved", "Replacement Approved"),
                    ("replacement_processing", "Replacement Processing"),
                    ("new_shipment_created", "New Shipment Created"),
                    ("new_shipment_in_transit", "New Shipment in Transit"),
                    ("replacement_shipped", "Replacement Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=30,
                verbose_name="To Status",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reverse_shipment_created", "Reverse Shipment Created"),
                    ("pickup_pending", "Pickup Pending"),
                    ("pickup_scheduled", "Pickup Scheduled"),
                    ("pickup_attempted", "Pickup Attempted"),
                    ("picked_up", "Picked Up"),
                    ("return_in_transit", "Return in Transit"),
                    ("return_delivered", "Return Delivered"),
                    ("item_received", "Item Received"),
                    ("qc_pending", "QC Pending"),
                    ("qc_passed", "QC Passed"),
                    ("qc_failed", "QC Failed"),
                    ("verification_pending", "Verification Pending"),
                    ("verification_passed", "Verification Passed"),
                    ("verification_failed", "Verification Failed"),
                    ("pickup_failed", "Pickup Failed"),
                    ("return_lost", "Return Lost"),
                    ("refund_pending", "Refund Pending"),
                    ("refund_processing", "Refund Processing"),
                    ("refunded", "Refunded"),
                    ("replacement_pending", "Replacement Pending"),
                    ("replacement_approved", "Replacement Approved"),
                    ("replacement_processing", "Replacement Processing"),
                    ("new_shipment_created", "New Shipment Created"),
                    ("new_shipment_in_transit", "New Shipment in Transit"),
                    ("replacement_shipped", "Replacement Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="requested",
                max_length=30,
                verbose_name="Return Status",
            ),
        ),
        migrations.AlterField(
            model_name="returnshipment",
            name="awb_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, verbose_name="AWB Number"
            ),
        ),
        migrations.AlterField(
            model_name="returnshipment",
            name="courier_name",
            field=models.CharField(
                default="Shiprocket Return", max_length=100, verbose_name="Courier Name"
            ),
        ),
        migrations.CreateModel(
            name="ReturnShipmentTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("event_code", models.CharField(max_length=50, verbose_name="Event Code")),
                ("event_label", models.CharField(max_length=150, verbose_name="Event Label")),
                (
                    "status_mapped",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Status Mapped"
                    ),
                ),
                ("event_timestamp", models.DateTimeField(verbose_name="Event Timestamp")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Location"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                (
                    "event_source",
                    models.CharField(default="webhook", max_length=30, verbose_name="Event Source"),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="returns.returnshipment",
                        verbose_name="Return Shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Shipment Tracking Event",
                "verbose_name_plural": "Return Shipment Tracking Events",
                "ordering": ["-event_timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("passed", "Verification Passed"),
                            ("failed", "Verification Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Verified At"),
                ),
                (
                    "verifier_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Verifier / Courier Executive Name",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, default="", verbose_name="Failure Reason"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Verification Notes"),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="returns/verification/%Y/%m/",
                        verbose_name="Verification Photo Evidence",
                    ),
                ),
                (
                    "return_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="returns.returnrequest",
                        verbose_name="Return Request",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By (Admin / Staff)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Verification",
                "verbose_name_plural": "Return Verifications",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
