# Generated by Django 5.2.15 on 2026-07-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_product_serial_number_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Solution Title")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Short Description"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Detailed Description / Clinical Overview"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solutions/banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "banner_image_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Banner Image URL"
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solutions/thumbnails/",
                        verbose_name="Thumbnail Image",
                    ),
                ),
                (
                    "thumbnail_image_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Thumbnail Image URL"
                    ),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "show_on_homepage",
                    models.BooleanField(default=True, verbose_name="Show on Homepage"),
                ),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=255, verbose_name="SEO Title"),
                ),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                (
                    "seo_keywords",
                    models.CharField(blank=True, max_length=255, verbose_name="SEO Keywords"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinical Solution",
                "verbose_name_plural": "Clinical Solutions",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalSolutionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Is Featured Inside Solution"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinical_solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_products",
                        to="solutions.clinicalsolution",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_mappings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Solution Product Mapping",
                "verbose_name_plural": "Clinical Solution Product Mappings",
                "ordering": ["-is_featured", "display_order", "id"],
                "unique_together": {("clinical_solution", "product")},
            },
        ),
    ]
