# Generated by Django 5.1 on 2026-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicalsolution",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Clinical Solution",
                "verbose_name_plural": "Clinical Solutions",
            },
        ),
        migrations.AddField(
            model_name="clinicalsolution",
            name="card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solutions/cards/",
                verbose_name="Homepage Card Image",
            ),
        ),
        migrations.AddField(
            model_name="clinicalsolution",
            name="card_image_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Card Image URL"
            ),
        ),
    ]
