# Generated by Django 5.1 on 2026-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="badge",
            field=models.CharField(
                blank=True, default="Limited Time", max_length=100, verbose_name="Badge"
            ),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="brand",
            field=models.CharField(
                blank=True, default="FAAZO Certified", max_length=100, verbose_name="Brand"
            ),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="category",
            field=models.CharField(
                blank=True, default="Equipment", max_length=100, verbose_name="Category"
            ),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="discounted_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Discounted Price"
            ),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, verbose_name="Image URL"),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Featured Promotion"
            ),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Original Price"
            ),
        ),
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="validity_text",
            field=models.CharField(
                blank=True,
                default="Valid while stock lasts",
                max_length=200,
                verbose_name="Validity & Stock Note",
            ),
        ),
    ]
