# Generated by Django 5.1 on 2026-09-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_limitedtimeoffer_badge_limitedtimeoffer_brand_and_more"),
        ("products", "0006_product_is_returnable"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitedtimeoffer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a real catalogue product for direct cart/inventory connection.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="limited_time_offers",
                to="products.product",
                verbose_name="Associated Product",
            ),
        ),
        migrations.AlterField(
            model_name="limitedtimeoffer",
            name="brand",
            field=models.CharField(blank=True, max_length=100, verbose_name="Brand"),
        ),
        migrations.AlterField(
            model_name="limitedtimeoffer",
            name="category",
            field=models.CharField(blank=True, max_length=100, verbose_name="Category"),
        ),
    ]
