# Generated by Django 5.1 on 2026-09-05 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_limitedtimeoffer_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffersPageContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "hero_badge",
                    models.CharField(
                        blank=True,
                        default="PROFESSIONAL CLINICAL SAVINGS",
                        max_length=150,
                        verbose_name="Hero Badge",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        default="Special Offers",
                        max_length=200,
                        verbose_name="Hero Heading",
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        blank=True,
                        default="Discover exclusive deals, bundle offers and limited-time savings on premium certified dental equipment, imaging systems, and clinical consumables.",
                        verbose_name="Hero Description",
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        blank=True,
                        default="EXPLORE OFFERS",
                        max_length=100,
                        verbose_name="Hero CTA Text",
                    ),
                ),
                (
                    "hero_trust_text",
                    models.CharField(
                        blank=True,
                        default="✓ 100% Genuine Direct Import • Manufacturer Warranty",
                        max_length=255,
                        verbose_name="Hero Trust Statement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Offers Page Content",
                "verbose_name_plural": "Special Offers Page Content",
            },
        ),
    ]
