# Generated by Django 5.1 on 2026-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_specialofferspagecontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="limitedtimeoffer",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "Limited Time Offer",
                "verbose_name_plural": "Limited Time Offers",
            },
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image shown on the homepage collection section.",
                null=True,
                upload_to="homepage/collections/",
                verbose_name="Collection Image",
            ),
        ),
    ]
