# Generated by Django 5.1 on 2026-09-11 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_deduplicate_and_unique_homepage_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepagePromoBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="FAAZO SUPER DEALS ARE LIVE:",
                        max_length=150,
                        verbose_name="Promo Tag / Prefix",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="UP TO 50% OFF + EXTRA 10% OFF ON PREMIUM DENTAL BRANDS",
                        max_length=255,
                        verbose_name="Main Announcement Text",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        default="/offers",
                        help_text="Optional link e.g. /offers or /products",
                        max_length=300,
                        verbose_name="Click Link URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active / Visible"),
                ),
            ],
            options={
                "verbose_name": "Homepage Promo Banner",
                "verbose_name_plural": "Homepage Promo Banners",
            },
        ),
        migrations.AlterModelOptions(
            name="homepagebrand",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Homepage Brand",
                "verbose_name_plural": "Homepage Brands",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendedproduct",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recommended Product",
                "verbose_name_plural": "Recommended Products",
            },
        ),
    ]
