# Generated by Django 5.1 on 2026-09-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_homepagepromobanner_alter_homepagebrand_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredcollection",
            name="badge_bg_color",
            field=models.CharField(
                blank=True, default="#E6F3F5", max_length=30, verbose_name="Badge Background Color"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="badge_color",
            field=models.CharField(
                blank=True, default="#006670", max_length=30, verbose_name="Badge Text Color"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="badge_text",
            field=models.CharField(
                blank=True,
                default="FEATURED COLLECTION",
                max_length=100,
                verbose_name="Small Label / Badge Text",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="banner_layout",
            field=models.CharField(
                choices=[
                    ("split", "Split Image + Content"),
                    ("background", "Full Background Image"),
                    ("solid", "Solid / Gradient Minimal"),
                ],
                default="split",
                max_length=30,
                verbose_name="Banner Layout",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="bg_color",
            field=models.CharField(
                blank=True,
                default="#F0F7F7",
                help_text="Hex code (e.g. #F0F7F7) or linear-gradient string.",
                max_length=100,
                verbose_name="Banner Background Color / Gradient",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="content_width",
            field=models.CharField(
                choices=[
                    ("small", "Small (420px)"),
                    ("medium", "Medium (580px)"),
                    ("large", "Large (760px)"),
                    ("full", "Full Width"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Content Max Width",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_action_type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("category", "Product Category / Collection"),
                    ("brand", "Brand"),
                    ("url", "Custom URL / Internal Page"),
                ],
                default="url",
                max_length=30,
                verbose_name="CTA Destination Type",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_bg_color",
            field=models.CharField(
                blank=True,
                default="#006670",
                max_length=30,
                verbose_name="CTA Button Background Color",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_border_color",
            field=models.CharField(
                blank=True, default="#006670", max_length=30, verbose_name="CTA Button Border Color"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_open_in_new_tab",
            field=models.BooleanField(default=False, verbose_name="Open CTA In New Tab"),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_style",
            field=models.CharField(
                choices=[("filled", "Filled"), ("outline", "Outline"), ("ghost", "Ghost")],
                default="filled",
                max_length=20,
                verbose_name="CTA Button Style",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_target_id",
            field=models.CharField(
                blank=True,
                help_text="Selected Product SKU/ID, Category slug, or Brand slug.",
                max_length=255,
                verbose_name="CTA Target Identifier",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_text",
            field=models.CharField(
                default="Explore Collection", max_length=100, verbose_name="CTA Button Text"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_text_color",
            field=models.CharField(
                blank=True, default="#FFFFFF", max_length=30, verbose_name="CTA Button Text Color"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="cta_url",
            field=models.CharField(
                blank=True, default="/offers", max_length=500, verbose_name="CTA URL"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="description_color",
            field=models.CharField(
                blank=True, default="#475569", max_length=30, verbose_name="Description Color"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Schedule End Date"),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="heading_color",
            field=models.CharField(
                blank=True, default="#1E293B", max_length=30, verbose_name="Heading Color"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="heading_size",
            field=models.CharField(
                choices=[
                    ("medium", "Medium (32px)"),
                    ("large", "Large (40px)"),
                    ("xlarge", "Extra Large (48px)"),
                    ("jumbo", "Jumbo (56px)"),
                ],
                default="large",
                max_length=20,
                verbose_name="Heading Size",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="heading_weight",
            field=models.CharField(
                choices=[
                    ("normal", "Normal (400)"),
                    ("semibold", "Semi-Bold (600)"),
                    ("bold", "Bold (700)"),
                    ("extrabold", "Extra-Bold (800)"),
                    ("black", "Black / Heavy (900)"),
                ],
                default="black",
                max_length=20,
                verbose_name="Heading Weight",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="horizontal_alignment",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=20,
                verbose_name="Horizontal Text Alignment",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="image_fit",
            field=models.CharField(
                choices=[("cover", "Cover"), ("contain", "Contain")],
                default="cover",
                max_length=20,
                verbose_name="Image Fit",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="image_position",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right"), ("center", "Center")],
                default="right",
                max_length=20,
                verbose_name="Image Position (Split Layout)",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional mobile-specific image for responsive art direction.",
                null=True,
                upload_to="homepage/collections/mobile/",
                verbose_name="Mobile Banner Image",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="offer_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. UP TO 25% OFF or SPECIAL CLINICAL PROMO",
                max_length=100,
                verbose_name="Offer Text",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="overlay_gradient",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("dark", "Dark Contrast (for bright images)"),
                    ("light", "Light Subtle (for dark images)"),
                    ("teal", "Teal Brand Gradient"),
                ],
                default="dark",
                max_length=30,
                verbose_name="Overlay Gradient Type",
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="overlay_opacity",
            field=models.PositiveSmallIntegerField(
                default=40, help_text="Percentage from 0 to 100", verbose_name="Overlay Opacity %"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="secondary_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Secondary Text / Footnote"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Schedule Start Date"),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="vertical_alignment",
            field=models.CharField(
                choices=[("top", "Top"), ("center", "Center"), ("bottom", "Bottom")],
                default="center",
                max_length=20,
                verbose_name="Vertical Text Alignment",
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="description",
            field=models.TextField(blank=True, verbose_name="Collection Description / Subtitle"),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image shown on the promotional banner.",
                null=True,
                upload_to="homepage/collections/",
                verbose_name="Desktop Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Collection Title / Main Heading"),
        ),
    ]
