# Generated by Django 5.1 on 2026-09-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_featuredcollection_badge_bg_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredcollection",
            name="content_width",
            field=models.CharField(
                choices=[
                    ("narrow", "Narrow"),
                    ("medium", "Medium"),
                    ("wide", "Wide"),
                    ("full", "Full Width"),
                    ("small", "Small"),
                    ("large", "Large"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Content Max Width",
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="heading_size",
            field=models.CharField(
                choices=[
                    ("sm", "Small"),
                    ("md", "Medium"),
                    ("lg", "Large"),
                    ("xl", "Extra Large"),
                    ("2xl", "2XL / Jumbo"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("xlarge", "Extra Large"),
                    ("jumbo", "Jumbo"),
                ],
                default="lg",
                max_length=20,
                verbose_name="Heading Size",
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="heading_weight",
            field=models.CharField(
                choices=[
                    ("normal", "Normal (400)"),
                    ("medium", "Medium (500)"),
                    ("semibold", "Semi-Bold (600)"),
                    ("bold", "Bold (700)"),
                    ("extrabold", "Extra-Bold (800)"),
                    ("black", "Black / Heavy (900)"),
                ],
                default="black",
                max_length=20,
                verbose_name="Heading Weight",
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="overlay_gradient",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("left", "Left to Right"),
                    ("right", "Right to Left"),
                    ("top", "Top to Bottom"),
                    ("bottom", "Bottom to Top"),
                    ("radial", "Radial Glow"),
                    ("dark", "Dark Contrast"),
                    ("light", "Light Subtle"),
                    ("teal", "Teal Brand Gradient"),
                ],
                default="left",
                max_length=30,
                verbose_name="Overlay Gradient Type",
            ),
        ),
    ]
