# Generated by Django 5.1 on 2026-09-15 06:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_alter_featuredcollection_content_width_and_more"),
        ("products", "0006_product_is_returnable"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        default="🔥 DAILY DEALS",
                        max_length=100,
                        verbose_name="Badge / Label",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Big Savings Today", max_length=200, verbose_name="Section Heading"
                    ),
                ),
                (
                    "subheading",
                    models.TextField(
                        blank=True,
                        default="Limited-time deals on selected products.",
                        verbose_name="Subheading / Description",
                    ),
                ),
                (
                    "offer_text",
                    models.CharField(
                        blank=True,
                        default="UP TO 40% OFF",
                        max_length=100,
                        verbose_name="Offer Text / Discount Tag",
                    ),
                ),
                (
                    "secondary_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Secondary Text / Microcopy"
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount"),
                            ("flat", "Flat Discount"),
                            ("bogo", "Buy One Get One"),
                            ("limited", "Limited Time Deal"),
                            ("new_arrival", "New Arrival Deal"),
                            ("clearance", "Clearance"),
                            ("custom", "Custom Promotion"),
                        ],
                        default="percentage",
                        max_length=30,
                        verbose_name="Offer Type",
                    ),
                ),
                (
                    "desktop_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional promotional banner artwork for desktop.",
                        null=True,
                        upload_to="homepage/daily_offers/",
                        verbose_name="Desktop Banner Image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional mobile artwork.",
                        null=True,
                        upload_to="homepage/daily_offers/mobile/",
                        verbose_name="Mobile Banner Image",
                    ),
                ),
                (
                    "image_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                        ],
                        default="center",
                        max_length=20,
                        verbose_name="Image Position",
                    ),
                ),
                (
                    "image_fit",
                    models.CharField(
                        choices=[("cover", "Cover"), ("contain", "Contain"), ("auto", "Auto")],
                        default="cover",
                        max_length=20,
                        verbose_name="Image Fit",
                    ),
                ),
                (
                    "overlay_gradient",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("dark", "Dark Shadow"),
                            ("light", "Light Glow"),
                            ("fade-right", "Fade Right"),
                            ("fade-bottom", "Fade Bottom"),
                        ],
                        default="none",
                        max_length=50,
                        verbose_name="Overlay Style",
                    ),
                ),
                (
                    "overlay_opacity",
                    models.PositiveSmallIntegerField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Overlay Opacity %",
                    ),
                ),
                (
                    "horizontal_alignment",
                    models.CharField(
                        choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                        default="center",
                        max_length=20,
                        verbose_name="Horizontal Text Alignment",
                    ),
                ),
                (
                    "vertical_alignment",
                    models.CharField(
                        choices=[("top", "Top"), ("center", "Center"), ("bottom", "Bottom")],
                        default="center",
                        max_length=20,
                        verbose_name="Vertical Text Alignment",
                    ),
                ),
                (
                    "content_width",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("full", "Full Width"),
                        ],
                        default="large",
                        max_length=20,
                        verbose_name="Content Width",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("dark_premium", "Dark Premium"),
                            ("red_hot", "Red Hot Deal"),
                            ("orange_sale", "Orange Sale"),
                            ("teal_premium", "Teal Premium"),
                            ("minimal_light", "Minimal Light"),
                            ("custom", "Custom"),
                        ],
                        default="red_hot",
                        max_length=30,
                        verbose_name="Visual Theme Preset",
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#991B1B", max_length=50, verbose_name="Background Color"
                    ),
                ),
                (
                    "bg_gradient",
                    models.CharField(
                        blank=True,
                        default="linear-gradient(135deg, #7F1D1D 0%, #DC2626 50%, #991B1B 100%)",
                        max_length=255,
                        verbose_name="Background Gradient",
                    ),
                ),
                (
                    "heading_color",
                    models.CharField(
                        default="#FFFFFF", max_length=50, verbose_name="Heading Color"
                    ),
                ),
                (
                    "description_color",
                    models.CharField(
                        default="#FEE2E2", max_length=50, verbose_name="Description Color"
                    ),
                ),
                (
                    "badge_bg_color",
                    models.CharField(
                        default="#FEF3C7", max_length=50, verbose_name="Badge Background Color"
                    ),
                ),
                (
                    "badge_text_color",
                    models.CharField(
                        default="#B45309", max_length=50, verbose_name="Badge Text Color"
                    ),
                ),
                (
                    "offer_color",
                    models.CharField(
                        default="#FDE047",
                        max_length=50,
                        verbose_name="Offer / Highlight Text Color",
                    ),
                ),
                (
                    "cta_bg_color",
                    models.CharField(
                        default="#FBBF24", max_length=50, verbose_name="CTA Background Color"
                    ),
                ),
                (
                    "cta_text_color",
                    models.CharField(
                        default="#78350F", max_length=50, verbose_name="CTA Text Color"
                    ),
                ),
                (
                    "cta_border_color",
                    models.CharField(
                        blank=True,
                        default="#F59E0B",
                        max_length=50,
                        verbose_name="CTA Border Color",
                    ),
                ),
                (
                    "countdown_bg_color",
                    models.CharField(
                        default="#000000", max_length=50, verbose_name="Countdown Box Background"
                    ),
                ),
                (
                    "countdown_text_color",
                    models.CharField(
                        default="#FFFFFF", max_length=50, verbose_name="Countdown Text Color"
                    ),
                ),
                (
                    "product_badge_color",
                    models.CharField(
                        default="#DC2626",
                        max_length=50,
                        verbose_name="Product Discount Badge Color",
                    ),
                ),
                (
                    "countdown_enabled",
                    models.BooleanField(default=True, verbose_name="Enable Countdown Timer"),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Start Date & Time"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="End Date & Time"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Shop Today's Deals →",
                        max_length=100,
                        verbose_name="CTA Button Text",
                    ),
                ),
                (
                    "cta_action_type",
                    models.CharField(
                        choices=[
                            ("product", "Specific Product"),
                            ("category", "Product Category"),
                            ("brand", "Brand"),
                            ("collection", "Product Collection"),
                            ("url", "Custom URL"),
                        ],
                        default="url",
                        max_length=30,
                        verbose_name="CTA Destination Type",
                    ),
                ),
                (
                    "cta_target_id",
                    models.CharField(
                        blank=True,
                        help_text="Selected Product SKU/ID, Category slug, or Brand slug.",
                        max_length=255,
                        verbose_name="CTA Target Identifier",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True, default="/offers", max_length=500, verbose_name="CTA URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("expired", "Expired"),
                            ("disabled", "Disabled"),
                        ],
                        default="live",
                        max_length=20,
                        verbose_name="Publication Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active / Visible"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Offer / Hot Deal",
                "verbose_name_plural": "Daily Offers / Hot Deals",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyOfferProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "deal_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override regular selling price specifically for this daily deal.",
                        max_digits=12,
                        null=True,
                        verbose_name="Custom Deal Price (Optional)",
                    ),
                ),
                (
                    "badge_override",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'HOT DEAL', 'LIMITED DEAL', '50% OFF'.",
                        max_length=50,
                        verbose_name="Badge Override",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "daily_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="homepage.dailyoffer",
                        verbose_name="Daily Offer Section",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_offer_entries",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Offer Product",
                "verbose_name_plural": "Daily Offer Products",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
