# Generated by Django 5.1 on 2026-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_dailyoffer_dailyofferproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyoffer",
            name="countdown_position",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=20,
                verbose_name="Countdown Alignment",
            ),
        ),
        migrations.AddField(
            model_name="dailyoffer",
            name="cta_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable CTA Button"),
        ),
        migrations.AddField(
            model_name="dailyoffer",
            name="cta_position",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=20,
                verbose_name="CTA Button Alignment",
            ),
        ),
        migrations.AddField(
            model_name="dailyoffer",
            name="font_family",
            field=models.CharField(
                blank=True, default="Inter", max_length=50, verbose_name="Font Family / Style"
            ),
        ),
        migrations.AddField(
            model_name="featuredcollection",
            name="font_family",
            field=models.CharField(
                blank=True, default="Inter", max_length=50, verbose_name="Font Family / Style"
            ),
        ),
        migrations.AlterField(
            model_name="dailyoffer",
            name="badge_text",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Badge / Label"
            ),
        ),
        migrations.AlterField(
            model_name="dailyoffer",
            name="cta_text",
            field=models.CharField(
                blank=True,
                default="Shop Today's Deals →",
                max_length=100,
                verbose_name="CTA Button Text",
            ),
        ),
        migrations.AlterField(
            model_name="dailyoffer",
            name="offer_text",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Offer Text / Discount Tag"
            ),
        ),
        migrations.AlterField(
            model_name="dailyoffer",
            name="secondary_text",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Secondary Text / Microcopy"
            ),
        ),
        migrations.AlterField(
            model_name="dailyoffer",
            name="subheading",
            field=models.TextField(blank=True, default="", verbose_name="Subheading / Description"),
        ),
        migrations.AlterField(
            model_name="dailyoffer",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Section Heading"
            ),
        ),
        migrations.AlterField(
            model_name="featuredcollection",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Collection Title / Main Heading",
            ),
        ),
    ]
