# Generated by Django 5.1 on 2026-09-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_dailyoffer_countdown_position_dailyoffer_cta_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagepromobanner",
            name="bg_color",
            field=models.CharField(
                blank=True,
                default="#005F63",
                help_text="Hex color or CSS color string for background, e.g. #005F63",
                max_length=50,
                verbose_name="Banner Background Color",
            ),
        ),
        migrations.AddField(
            model_name="homepagepromobanner",
            name="border_color",
            field=models.CharField(
                blank=True,
                default="#005F63",
                help_text="Hex color for optional border, e.g. #005F63",
                max_length=50,
                verbose_name="Border Color",
            ),
        ),
        migrations.AddField(
            model_name="homepagepromobanner",
            name="tagline_color",
            field=models.CharField(
                blank=True,
                default="#BFE8E8",
                help_text="Hex color for top accent text, e.g. #BFE8E8",
                max_length=50,
                verbose_name="Tagline Text Color",
            ),
        ),
        migrations.AddField(
            model_name="homepagepromobanner",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="#FFFFFF",
                help_text="Hex color for main offer text, e.g. #FFFFFF",
                max_length=50,
                verbose_name="Main Text Color",
            ),
        ),
    ]
