# Generated by Django 5.1 on 2026-09-18 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_alter_brand_options_brand_banner_image_and_more"),
        ("homepage", "0012_homepagepromobanner_bg_color_and_more"),
        ("products", "0006_product_is_returnable"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandDeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "name",
                    models.CharField(
                        help_text="Internal campaign name e.g. 'Woodpecker Super Deal Week'.",
                        max_length=200,
                        verbose_name="Campaign Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique URL slug e.g. 'woodpecker-special-offer'.",
                        max_length=220,
                        unique=True,
                        verbose_name="Campaign Slug",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main banner headline e.g. 'Woodpecker Special Offer'.",
                        max_length=255,
                        verbose_name="Promotional Headline",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Special prices on selected clinical products'.",
                        max_length=300,
                        verbose_name="Subtitle / Offer Subheading",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed campaign description shown on the campaign landing page.",
                        verbose_name="Campaign Description",
                    ),
                ),
                (
                    "promotional_tag",
                    models.CharField(
                        blank=True,
                        default="EXCLUSIVE BRAND OFFER",
                        help_text="e.g. 'EXCLUSIVE BRAND OFFER', 'LIMITED BRAND DEAL'.",
                        max_length=100,
                        verbose_name="Promotional Label / Badge",
                    ),
                ),
                (
                    "offer_text",
                    models.CharField(
                        blank=True,
                        default="UP TO 40% OFF",
                        help_text="e.g. 'UP TO 50% OFF', 'SPECIAL INTRODUCTORY PRICES'.",
                        max_length=100,
                        verbose_name="Offer / Discount Callout",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        default="Shop the Offer →",
                        max_length=100,
                        verbose_name="CTA Button Text",
                    ),
                ),
                (
                    "desktop_image",
                    models.ImageField(
                        blank=True,
                        help_text="Promotional banner artwork for desktop display.",
                        null=True,
                        upload_to="homepage/brand_deals/",
                        verbose_name="Desktop Banner Image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional mobile artwork.",
                        null=True,
                        upload_to="homepage/brand_deals/mobile/",
                        verbose_name="Mobile Banner Image",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="If disabled, banner will not appear on homepage but landing page remains active.",
                        verbose_name="Show on Homepage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Campaign Status",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the campaign automatically goes live.",
                        null=True,
                        verbose_name="Start Date & Time",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the campaign and its pricing automatically expire.",
                        null=True,
                        verbose_name="End Date & Time",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Master toggle to enable/disable the campaign.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "is_all_brand_products",
                    models.BooleanField(
                        default=False,
                        help_text="If true, all active products of this brand participate.",
                        verbose_name="Include All Brand Products",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_campaigns",
                        to="brands.brand",
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Deal Campaign",
                "verbose_name_plural": "Brand Deal Campaigns",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrandDealProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "deal_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Authoritative promotional selling price for this product during the campaign.",
                        max_digits=12,
                        verbose_name="Campaign Deal Price (GST Inclusive)",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated automatically vs MRP or entered directly.",
                        max_digits=5,
                        null=True,
                        verbose_name="Discount Percentage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active in Deal")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "brand_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_products",
                        to="homepage.branddeal",
                        verbose_name="Brand Deal Campaign",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_deal_entries",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Deal Product",
                "verbose_name_plural": "Brand Deal Products",
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("brand_deal", "product")},
            },
        ),
    ]
