# Generated by Django 5.1 on 2026-09-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_branddeal_branddealproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="branddeal",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="#BFE8E8",
                help_text="Hex color code for promotional tag and accents e.g. #BFE8E8.",
                max_length=50,
                verbose_name="Banner Accent / Tag Color",
            ),
        ),
        migrations.AddField(
            model_name="branddeal",
            name="bg_color",
            field=models.CharField(
                blank=True,
                default="#005F63",
                help_text="Hex color code for background e.g. #005F63.",
                max_length=50,
                verbose_name="Banner Background Color",
            ),
        ),
        migrations.AddField(
            model_name="branddeal",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="#FFFFFF",
                help_text="Hex color code for headline and main text e.g. #FFFFFF.",
                max_length=50,
                verbose_name="Banner Text Color",
            ),
        ),
    ]
